### ISSUE TITLE
what is this???? no documnetation no exameples nothing why?

### ISSUE THREAD

**Issue by fisforfaheem** [aloisdeniel/figma-to-flutter#13]
please do some thing

**Comment by aloisdeniel** [comment]
I'm working on it. Remember that's an open source project and I'm not paid for it. If you want this to be prioritized, you're welcome to sponsor me!

**Comment by fisforfaheem** [comment]
i mean it's been a lot of time...atleast add some documentation...or mske
this paid (service) or anything/

**Comment by aloisdeniel** [comment]
This looks like documentation to me...
 
* [figma_theme_generator](https://github.com/aloisdeniel/figma-to-flutter/tree/master/figma_theme_generator)
* [figma_to_flutter](https://github.com/aloisdeniel/figma-to-flutter/tree/master/figma_to_flutter)

**Comment by fisforfaheem** [comment]
on GITHUB main PAGE!

**Comment by nightscape** [comment]
@fisforfaheem I'm not involved with this project but I maintain other open source projects.
If you want to get support from someone you're not paying, I would recommend you to ask your questions kindly and not as if you were the maintainer's boss giving him instructions.

**Comment by fisforfaheem** [comment]
I was suggesting....as this could bring him huge amounts of money.
