### ISSUE TITLE
Uncaught Error: Instance of 'FigmaFormattingException'

### ISSUE THREAD

**Issue by lennybakkalian** [aloisdeniel/figma-to-flutter#3]
Hey,
do you have a idea how to Fix this kind of exception?
![image](https://user-images.githubusercontent.com/26249979/44294192-9cd69180-a293-11e8-8d80-00192801cf6c.png)

**Comment by lennybakkalian** [comment]
now i found the root issue. this exception will throw when i have a text with line breaks...

**Comment by aloisdeniel** [comment]
Oh thanks for noticing, i’ll look into it!
