### ISSUE TITLE
Is this project stopped?

### ISSUE THREAD

**Issue by eugenejeonme** [aloisdeniel/figma-to-flutter#5]
I feel so sad because it seems to have stopped...:(

![image](https://user-images.githubusercontent.com/36671804/61014921-a2b1f580-a3c4-11e9-992f-88cc7a8c5083.png)

**Comment by aloisdeniel** [comment]
No, I'm just waiting for the [Figma plugin API](https://www.figma.com/blog/plugins-are-coming-to-figma/) to be released ! This way you should be able to export code right from the editor !

Stay tuned.
